name: Generate JSON files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install fs path

    - name: Generate JSON files
      run: node generate.js

    - name: Commit and push if it changed
      run: |
        git diff
        git diff-index --quiet HEAD || echo "files changed" || exit 1
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "Automated JSON files update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
