name: Copy and Rename JSON Files
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install fs-extra

    - name: Run Script
      run: |
        node -e "\
        const fs = require('fs-extra');\
        const path = require('path');\
        \
        const sourceDir = './CNC-Raffle';\
        const targetDir = './CNC-Raffle/NMKR';\
        \
        fs.ensureDirSync(targetDir);\
        \
        for(let i = 1; i <= 600; i++) {\
            let filename = 'CNCAlaRaffle#' + ('000' + i).slice(-3) + '.metadata.json';\
            let sourcePath = path.join(sourceDir, filename);\
            \
            let newFilename = 'CNCAlaRaffle#' + ('000' + i).slice(-3) + '.metadata';\
            let targetPath = path.join(targetDir, newFilename);\
            \
            fs.copySync(sourcePath, targetPath);\
        }\
        console.log('Files have been copied and renamed.');\
        "

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CNC-Raffle/NMKR/*
        git diff --quiet && git diff --staged --quiet || git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}

