name: Generate NFT meta JSON files

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14'

    - name: Generate JSON files
      run: |
        echo 'Generating NFT meta JSON files...'

        const fs = require('fs');
        const path = require('path');

        const baseDir = './CNC-Raffle';
        const filePath = path.join(baseDir, 'CNCAlaRaffle#000.metadata.json');
        let rawdata = fs.readFileSync(filePath);
        let jsondata = JSON.parse(rawdata);

        for(let i = 1; i <= 600; i++) {
            let newdata = JSON.parse(JSON.stringify(jsondata));
            newdata['721']['<policy_id>']['<asset_name>']['3_Attributes/']['Ticket:'] = i;
            let filename = 'CNCAlaRaffle#' + ('000' + i).slice(-3) + '.metadata.json';
            let newFilePath = path.join(baseDir, filename);
            fs.writeFileSync(newFilePath, JSON.stringify(newdata, null, 2));
        }

        console.log('JSON files have been generated.');

    - name: Commit and push if it changed
      run: |
        git diff
        git diff-index --quiet HEAD || echo "files changed" || exit 1
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Automated JSON files update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
